imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    images_directory: '%kernel.root_dir%/../web/uploads/photos'

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
# app/config/config.yml
twig:
    form:
        resources: ['bootstrap_3_layout.html.twig']
        #resources: ['bootstrap_3_horizontal_layout.html.twig']
# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                dql:
                    numeric_functions:
                        ACOS: DoctrineExtensions\Query\Mysql\Acos
                        ASIN: DoctrineExtensions\Query\Mysql\Asin
                        SIN: DoctrineExtensions\Query\Mysql\Sin
                        COS: DoctrineExtensions\Query\Mysql\Cos
                        RADIANS: DoctrineExtensions\Query\Mysql\Radians
        #naming_strategy: doctrine.orm.naming_strategy.underscore
        #auto_mapping: true


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: UserBundle\Entity\User

    registration:
         form:
             #type: AppBundle\Form\RegistrationType
             # if you are using Symfony < 2.8 you should use the type name instead
             type: app_user_registration
         confirmation:
             enabled: true
             from_email:
                 address:  "%mailer_user%"
                 sender_name: "%sender_name%"

fos_message:
    db_driver: orm
    thread_class: MessageBundle\Entity\Thread
    message_class: MessageBundle\Entity\Message
    message_manager:        fos_message.message_manager.default         # See ModelManager\MessageManagerInterface
#    thread_manager:         fos_message.thread_manager.default          # See ModelManager\ThreadManagerInterface
#    sender:                 fos_message.sender.default                  # See Sender\SenderInterface
#    composer:               fos_message.composer.default                # See Composer\ComposerInterface
#    provider:               fos_message.provider.default                # See Provider\ProviderInterface
#    participant_provider:   fos_message.participant_provider.default    # See Security\ParticipantProviderInterface
#    authorizer:             fos_message.authorizer.default              # See Security\AuthorizerInterface
#    message_reader:         fos_message.message_reader.default          # See Reader\ReaderInterface
#    thread_reader:          fos_message.thread_reader.default           # See Reader\ReaderInterface
#    deleter:                fos_message.deleter.default                 # See Deleter\DeleterInterface
#    spam_detector:          fos_message.noop_spam_detector      # See SpamDetection\SpamDetectorInterface
#    twig_extension:         fos_message.twig_extension.default          # See Twig\Extension\MessageExtension
#    user_transformer:       fos_user.user_transformer           # See Symfony\Component\Form\DataTransformerInterface
#    search:
#        finder:             fos_message.search_finder.default           # See Finder\FinderInterface
#        query_factory:      fos_message.search_query_factory.default    # See Finder\QueryFactoryInterface
#        query_parameter:    'q'                                     # Request query parameter containing the term
    new_thread_form:
        factory:              fos_message.new_thread_form.factory.default
        type:                 fos_message.new_thread_form.type.default
        handler:              fos_message.new_thread_form.handler.default
        name:                 message
        model:                FOS\MessageBundle\FormModel\NewThreadMessage
    reply_form:
        factory:              fos_message.reply_form.factory.default
        type:                 fos_message.reply_form.type.default
        handler:              fos_message.reply_form.handler.default
        name:                 message


